tidy:
  breakend:
    description: 'Telomeric rearrangements.'
    schema:
      latest:
        tbl1:
        - field: 'chrom'
          type: 'char'
          description: 'Chromosome of breakend'
        - field: 'position'
          type: 'float'
          description: 'Position of Breakend'
        - field: 'orientation'
          type: 'float'
          description: '1 = breakend on left side; -1 = breakend on right side'
        - field: 'cg_rich'
          type: 'char'
          description: 'C or G'
        - field: 'filter'
          type: 'char'
          description: 'PASS or one or more of the specified filters'
        - field: 'in_tumor'
          type: 'char'
          description: 'true if in tumor'
        - field: 'in_germline'
          type: 'char'
          description: 'true if in germline'
        - field: 'distance_to_telomere'
          type: 'float'
          description: 'Distance to nearest reference telomere in nucleotides'
        - field: 'max_telomeric_length'
          type: 'float'
          description: 'Longest continuous telomeric segment on any fragment supporting the rearrangement'
        - field: 'max_anchor_length'
          type: 'float'
          description: 'Longest locally anchored segment on any fragment supporting the rearrangement'
        - field: 'tumor_sr_tel_dp_tel'
          type: 'float'
          description: 'Count of fragments in tumor with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read discordant and containing telomeric sequence'
        - field: 'tumor_sr_tel_dp_no_tel'
          type: 'float'
          description: 'Count of fragments in tumor with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read discordant but not containing telomeric sequence (may indicate telomeric insertion)'
        - field: 'tumor_sr_tel_no_dp'
          type: 'float'
          description: 'Count of fragments in tumor with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read locally anchored'
        - field: 'tumor_sr_no_tel_dp_tel'
          type: 'float'
          description: 'Count of fragments in tumor with 1 read with soft clip supporting the breakend but NOT containing telomeric sequence with the paired read discordant and containing telomeric sequence'
        - field: 'tumor_dp_tel_no_sr'
          type: 'float'
          description: 'Count of fragments in tumor with 1 read locally anchored but not spanning the breakend and the paired read discordant and containing telomeric sequence'
        - field: 'tumor_total_support'
          type: 'float'
          description: 'Tumor total support'
        - field: 'tumor_mapq'
          type: 'float'
          description: 'Sum of MAPQ of locally anchored reads in fragments supporting the rearrangement in tumor'
        - field: 'germ_sr_tel_dp_tel'
          type: 'float'
          description: 'Count of fragments in germline with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read discordant and containing telomeric sequence'
        - field: 'germ_sr_tel_dp_no_tel'
          type: 'float'
          description: 'Count of fragments in germline with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read discordant but not containing telomeric sequence (may indicate telomeric insertion)'
        - field: 'germ_sr_tel_no_dp'
          type: 'float'
          description: 'Count of fragments in germline with 1 read with soft clip supporting the breakend and containing telomeric sequence with the paired read locally anchored'
        - field: 'germ_sr_no_tel_dp_tel'
          type: 'float'
          description: 'Count of fragments in germline with 1 read with soft clip supporting the breakend but NOT containing telomeric sequence with the paired read discordant and containing telomeric sequence'
        - field: 'germ_dp_tel_no_sr'
          type: 'float'
          description: 'Count of fragments in germline with 1 read locally anchored but not spanning the breakend and the paired read discordant and containing telomeric sequence'
        - field: 'germ_total_support'
          type: 'float'
          description: 'Germline total support'
        - field: 'germ_mapq'
          type: 'float'
          description: 'Sum of MAPQ of locally anchored reads in fragments supporting the rearrangement in germline'
  tellength:
    description: 'Telomeric length and content.'
    schema:
      latest:
        tbl1:
        - field: 'sample_id'
          type: 'char'
          description: 'Sample ID'
        - field: 'type'
          type: 'char'
          description: 'tumor or ref'
        - field: 'tel_length_raw'
          type: 'float'
          description: 'Raw telomere length'
        - field: 'tel_length_final'
          type: 'float'
          description: 'Final telomere length adjusted for purity (= raw length for ref sample)'
        - field: 'fragments_full'
          type: 'float'
          description: 'Count of fragments with both reads classified as telomeric'
        - field: 'fragments_c_rich_partial'
          type: 'float'
          description: 'Count of fragments with 1 read non telomeric and the other telomeric oriented in a C-rich orientation'
        - field: 'fragments_g_rich_partial'
          type: 'float'
          description: 'Count of fragments with 1 read non telomeric and the other telomeric oriented in a G-rich orientation'
        - field: 'reads_telomeric_total'
          type: 'float'
          description: 'Total telomeric reads'
        - field: 'purity'
          type: 'float'
          description: 'Purity from PURPLE (=1 for ref)'
        - field: 'ploidy'
          type: 'float'
          description: 'Ploidy from PURPLE (=2 for ref)'
        - field: 'dup_prop'
          type: 'float'
          description: 'Duplicate proportion (from WGS metrics)'
        - field: 'dp_read_mean'
          type: 'float'
          description: 'Mean read depth (from COBALT)'
        - field: 'dp_read_gc50'
          type: 'float'
          description: 'Read depth GC 50 (from COBALT)'

