project:
  type: website
  # render:
  #   - index.qmd
  #   - neo.qmd
format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
website:
  title: "tidywigits"
  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: purple.qmd
        text: PURPLE
      - href: amber.qmd
        text: AMBER
      - href: bamtools.qmd
        text: BAMTOOLS
      - href: chord.qmd
        text: CHORD
      - href: cider.qmd
        text: CIDER
      - href: cuppa.qmd
        text: CUPPA
      - href: lilac.qmd
        text: LILAC
      - href: neo.qmd
        text: NEO
      - href: peach.qmd
        text: PEACH
      - href: sigs.qmd
        text: SIGS
      - href: teal.qmd
        text: TEAL
      - href: virus.qmd
        text: VIRUS
      - href: versions.qmd
        text: Versions
#  sidebar:
#    style: floating
#    search: true
#    contents:
#      - index.qmd
#      - purple.qmd
#      - amber.qmd
