project:
  type: website

website:
  title: "tidywigits"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: purple.qmd
        text: PURPLE
      - href: amber.qmd
        text: AMBER

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
