tidy:
  summary:
    description: 'QC summary.'
    schema:
      latest:
        tbl1:
          - field: 'sample_id'
            type: 'char'
            description: 'sample ID'
          - field: 'qc_status'
            type: 'char'
            description: 'QC status'
          - field: 'frag_tot'
            type: 'float'
            description: 'total fragments'
          - field: 'frag_dup'
            type: 'float'
            description: 'duplicate marked fragments'
          - field: 'frag_spliced_pct'
            type: 'float'
            description: 'fragment % supporting 1 or more known transcripts'
          - field: 'frag_unspliced_pct'
            type: 'float'
            description: 'fragment % not containing a splice junction and not supporting any known transcript'
          - field: 'frag_alt_pct'
            type: 'float'
            description: 'fragment % supporting an alternate splice junction within a gene'
          - field: 'frag_chimeric_pct'
            type: 'float'
            description: 'fragment % supporting a chimeric junction'
          - field: 'spliced_gene_count'
            type: 'float'
            description: 'count of spliced genes'
          - field: 'read_length'
            type: 'float'
            description: 'raw read length of fragments'
          - field: 'frag_length_5th'
            type: 'float'
            description: '5th percentile of genic intronic fragment lengths'
          - field: 'frag_length_50th'
            type: 'float'
            description: '50th percentile of genic intronic fragment lengths'
          - field: 'frag_length_95th'
            type: 'float'
            description: '95th percentile of genic intronic fragment lengths'
          - field: 'enriched_gene_pct'
            type: 'float'
            description: 'fragment % supporting one of the following 6 genes: RN7SL2, RN7SL1, RN7SL3, RN7SL4P, RN7SL5P & RN7SK'
          - field: 'median_gc_ratio'
            type: 'float'
            description: 'median GC ratio excluding the 6 highly enriched genes'
          - field: 'forward_strand_pct'
            type: 'float'
            description: ''
  genedata:
    description: 'Gene level data.'
    schema:
      latest:
        tbl1:
          - field: 'gene_id'
            type: 'char'
            description: 'Ensembl gene id'
          - field: 'gene_name'
            type: 'char'
            description: 'Gene name'
          - field: 'chrom'
            type: 'char'
            description: 'chromosome'
          - field: 'gene_length'
            type: 'int'
            description: 'length of gene'
          - field: 'intronic_length'
            type: 'int'
            description: 'total bases which are intronic across all transcripts'
          - field: 'transcript_count'
            type: 'int'
            description: 'count of transcripts in gene'
          - field: 'gene_set_id'
            type: 'char'
            description: 'identifier shared by all genes in overlapping group'
          - field: 'spliced_fragments'
            type: 'int'
            description: 'count of fitted fragments assigned to spliced transcripts in the gene'
          - field: 'unspliced_fragments'
            type: 'int'
            description: 'count of fitted fragments assigned to the unspliced gene transcript'
          - field: 'tpm_adj'
            type: 'float'
            description: 'adjusted TPM'
          - field: 'tpm_raw'
            type: 'float'
            description: 'raw TPM'
          - field: 'fit_residuals'
            type: 'float'
            description: 'fit residuals'
          - field: 'low_map_quality_fragments'
            type: 'float'
            description: ''
  transdata:
    description: 'Transcript level data.'
    schema:
      latest:
        tbl1:
          - field: 'gene_id'
            type: 'char'
            description: 'Ensembl ID for gene'
          - field: 'gene_name'
            type: 'char'
            description: 'gene name'
          - field: 'transcript_id'
            type: 'char'
            description: 'Ensembl ID for transcript'
          - field: 'transcript_name'
            type: 'char'
            description: 'Ensembl transcript name'
          - field: 'exon_count'
            type: 'int'
            description: 'count of exons in transcript'
          - field: 'transcript_length'
            type: 'int'
            description: 'total length of transcript'
          - field: 'effective_length'
            type: 'int'
            description: 'effective length of transcript (adjusted for fragment size)'
          - field: 'fitted_fragments'
            type: 'float'
            description: 'count of fragments assigned to transcript'
          - field: 'raw_fitted_fragments'
            type: 'float'
            description: 'count of fragments assigned to transcript prior to bias adjustments'
          - field: 'tpm_adj'
            type: 'float'
            description: 'adjusted TPM'
          - field: 'tpm_raw'
            type: 'float'
            description: 'raw TPM'
          - field: 'transcript_bases_covered'
            type: 'float'
            description: 'number of bases in transcript with at least 1 supporting fragment'
          - field: 'sj_supported'
            type: 'float'
            description: 'count of splice junctions in transcript with at least 1 supporting fragment'
          - field: 'sj_supported_unique'
            type: 'float'
            description: 'count of unique splice junctions in transcript with at least 1 supporting fragment'
          - field: 'sj_fragments_unique'
            type: 'float'
            description: 'count of fragments supporting a splice junction unique to the transcript'
          - field: 'non_sj_fragments_unique'
            type: 'float'
            description: 'count of fragments uniquely supporting transcript but without a unique splice junction'
          - field: 'fragments_discordant'
            type: 'float'
            description: ''
          - field: 'low_map_quality_fragments'
            type: 'float'
            description: ''
  altsj:
    description: 'Alternate splice junctions.'
    schema:
      latest:
        tbl1:
          - field: 'gene_id'
            type: 'char'
            description: 'Ensembl ID for gene'
          - field: 'gene_name'
            type: 'char'
            description: 'gene name'
          - field: 'chrom'
            type: 'char'
            description: 'chromosome'
          - field: 'sj_start'
            type: 'float'
            description: 'start position of novel splice junction'
          - field: 'sj_end'
            type: 'float'
            description: 'end position of novel splice junction'
          - field: 'type'
            type: 'char'
            description: 'type of novel splice junction'
          - field: 'frag_count'
            type: 'float'
            description: 'fragment count'
          - field: 'dp_start'
            type: 'float'
            description: 'total depth at start_sj position'
          - field: 'dp_end'
            type: 'float'
            description: 'total depth at end_sj position'
          - field: 'region_start'
            type: 'char'
            description: ''
          - field: 'region_end'
            type: 'char'
            description: ''
          - field: 'bases_start'
            type: 'char'
            description: ''
          - field: 'bases_end'
            type: 'char'
            description: ''
          - field: 'trans_start'
            type: 'char'
            description: ''
          - field: 'trans_end'
            type: 'char'
            description: ''
          - field: 'nearest_start_exon'
            type: 'float'
            description: ''
          - field: 'nearest_end_exon'
            type: 'float'
            description: ''
          - field: 'init_read_id'
            type: 'char'
            description: ''
  retintron:
    description: 'Retained introns.'
    schema:
      latest:
        tbl1:
          - field: 'gene_id'
            type: 'char'
            description: 'Ensembl ID for gene'
          - field: 'gene_name'
            type: 'char'
            description: 'gene name'
          - field: 'chrom'
            type: 'char'
            description: 'chromosome'
          - field: 'strand'
            type: 'float'
            description: 'strand'
          - field: 'position'
            type: 'float'
            description: 'position of exon boundary with overlapping frags suggesting retained intron'
          - field: 'type'
            type: 'char'
            description: 'donor or acceptor splice site'
          - field: 'frag_count'
            type: 'float'
            description: 'Count of all fragments which overlap splice site boundary'
          - field: 'spliced_frag_count'
            type: 'float'
            description: 'Count of fragments which overlap splice site boundary which contain another splice site (ie. evidence of being part of a spliced transcript)'
          - field: 'dp_total'
            type: 'float'
            description: 'depth at splice boundary'
          - field: 'transcript_info'
            type: 'char'
            description: 'transcript ID and exon rank of all transcripts that match splice site boundary'
  fusionsall:
    description: 'All fusions.'
    schema:
      latest:
        tbl1:
          - field: 'fusion_id'
            type: 'char'
            description: 'fusion id'
          - field: 'valid'
            type: 'char'
            description: 'valid fusion'
          - field: 'chr_up'
            type: 'char'
            description: 'chromosome of up breakend'
          - field: 'pos_up'
            type: 'float'
            description: 'position of up breakend'
          - field: 'orient_up'
            type: 'char'
            description: 'orientation of up breakend'
          - field: 'gene_id_up'
            type: 'char'
            description: 'Ensembl ID of gene at up breakend'
          - field: 'gene_name_up'
            type: 'char'
            description: 'gene name at up breakend'
          - field: 'strand_up'
            type: 'char'
            description: 'strand of gene at up breakend'
          - field: 'junc_type_up'
            type: 'char'
            description: 'junction type at up breakend (known, canonical, unknown)'
          - field: 'coverage_up'
            type: 'float'
            description: 'n of fragments overlapping the last base prior to the up breakend'
          - field: 'max_anchor_length_up'
            type: 'float'
            description: 'maximum number of distinct matched bases by any 1 junction supporting fragment at the up breakend'
          - field: 'trans_data_up'
            type: 'char'
            description: 'transcript ids which contain a splice junction which includes matches the up breakend'
          - field: 'chr_down'
            type: 'char'
            description: 'chromosome of down breakend'
          - field: 'pos_down'
            type: 'float'
            description: 'position of down breakend'
          - field: 'orient_down'
            type: 'float'
            description: 'orientation of down breakend'
          - field: 'gene_id_down'
            type: 'char'
            description: 'Ensembl ID of gene at down breakend'
          - field: 'gene_name_down'
            type: 'char'
            description: 'gene name at down breakend'
          - field: 'strand_down'
            type: 'float'
            description: 'strand of gene at down breakend'
          - field: 'junc_type_down'
            type: 'char'
            description: 'junction type at down breakend (known, canonical, unknown)'
          - field: 'coverage_down'
            type: 'float'
            description: 'n of fragments overlapping the last base prior to the down breakend'
          - field: 'max_anchor_length_down'
            type: 'float'
            description: 'maximum number of distinct matched bases by any 1 junction supporting fragment at the down breakend'
          - field: 'trans_data_down'
            type: 'char'
            description: 'transcript ids which contain a splice junction which includes matches the down breakend'
          - field: 'sv_type'
            type: 'char'
            description: 'structural variant type'
          - field: 'total_frags'
            type: 'float'
            description: 'n fragments supporting the transcript = spliced + realigned + discordant'
          - field: 'split_frags'
            type: 'float'
            description: 'n fragments with supplementary or spliced alignments that match the chimeric junction'
          - field: 'realigned_frags'
            type: 'float'
            description: 'n fragments which overlap the breakpoint at either end by at least 3 bases and exactly match the reference sequence at the other breakend but are not split or spliced at the break junction by the aligner'
          - field: 'discordant_frags'
            type: 'float'
            description: ''
          - field: 'related_spliced_ids'
            type: 'char'
            description: ''
          - field: 'cohort_count'
            type: 'float'
            description: ''
          - field: 'read_type'
            type: 'char'
            description: 'read type'
          - field: 'init_read_id'
            type: 'char'
            description: ''
  fusionspass:
    description: 'Passed fusions.'
    schema:
      latest:
        tbl1:
          - field: 'fusion_id'
            type: 'char'
            description: 'fusion id'
          - field: 'valid'
            type: 'char'
            description: 'valid fusion'
          - field: 'chr_up'
            type: 'char'
            description: 'chromosome of up breakend'
          - field: 'pos_up'
            type: 'float'
            description: 'position of up breakend'
          - field: 'orient_up'
            type: 'float'
            description: 'orientation of up breakend'
          - field: 'gene_id_up'
            type: 'char'
            description: 'Ensembl ID of gene at up breakend'
          - field: 'gene_name_up'
            type: 'char'
            description: 'gene name at up breakend'
          - field: 'strand_up'
            type: 'float'
            description: 'strand of gene at up breakend'
          - field: 'junc_type_up'
            type: 'char'
            description: 'junction type at up breakend (known, canonical, unknown)'
          - field: 'coverage_up'
            type: 'float'
            description: 'n of fragments overlapping the last base prior to the up breakend'
          - field: 'max_anchor_length_up'
            type: 'float'
            description: 'maximum number of distinct matched bases by any 1 junction supporting fragment at the up breakend'
          - field: 'chr_down'
            type: 'char'
            description: 'chromosome of down breakend'
          - field: 'pos_down'
            type: 'float'
            description: 'position of down breakend'
          - field: 'orient_down'
            type: 'float'
            description: 'orientation of down breakend'
          - field: 'gene_id_down'
            type: 'char'
            description: 'Ensembl ID of gene at down breakend'
          - field: 'gene_name_down'
            type: 'char'
            description: 'gene name at down breakend'
          - field: 'strand_down'
            type: 'float'
            description: 'strand of gene at down breakend'
          - field: 'junc_type_down'
            type: 'char'
            description: 'junction type at down breakend (known, canonical, unknown)'
          - field: 'coverage_down'
            type: 'float'
            description: 'n of fragments overlapping the last base prior to the down breakend'
          - field: 'max_anchor_length_down'
            type: 'float'
            description: 'maximum number of distinct matched bases by any 1 junction supporting fragment at the down breakend'
          - field: 'sv_type'
            type: 'char'
            description: 'structural variant type'
          - field: 'total_frags'
            type: 'float'
            description: 'n fragments supporting the transcript = spliced + realigned + discordant'
          - field: 'split_frags'
            type: 'float'
            description: 'n fragments with supplementary or spliced alignments that match the chimeric junction'
          - field: 'realigned_frags'
            type: 'float'
            description: 'n fragments which overlap the breakpoint at either end by at least 3 bases and exactly match the reference sequence at the other breakend but are not split or spliced at the break junction by the aligner'
          - field: 'discordant_frags'
            type: 'float'
            description: ''
          - field: 'related_spliced_ids'
            type: 'char'
            description: ''
          - field: 'cohort_count'
            type: 'float'
            description: ''
          - field: 'filter'
            type: 'char'
            description: ''
          - field: 'known_fusion_type'
            type: 'char'
            description: ''
  genecollection:
    description: 'Gene collection.'
    schema:
      latest:
        tbl1:
          - field: 'gene_set_id'
            type: 'char'
            description: 'Gene set ID'
          - field: 'gene_count'
            type: 'float'
            description: 'Gene count'
          - field: 'chrom'
            type: 'char'
            description: 'chromosome'
          - field: 'range_start'
            type: 'float'
            description: ''
          - field: 'range_end'
            type: 'float'
            description: ''
          - field: 'total_frags'
            type: 'float'
            description: ''
          - field: 'duplicates'
            type: 'float'
            description: ''
          - field: 'supporting_trans'
            type: 'float'
            description: ''
          - field: 'unspliced'
            type: 'float'
            description: ''
          - field: 'alt_sj'
            type: 'float'
            description: ''
          - field: 'chimeric'
            type: 'float'
            description: ''
          - field: 'low_map_qual'
            type: 'float'
            description: ''
          - field: 'fwd_strand'
            type: 'float'
            description: ''
          - field: 'rev_strand'
            type: 'float'
            description: ''
          - field: 'genes'
            type: 'char'
            description: ''
