context:
  name: r-tidywigits
  version: 0.0.6.9001 # bump

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base
    - r-dplyr
    - r-fs
    - r-glue
    - r-knitr
    - r-nemo
    - r-purrr
    - r-r6
    - r-readr
    - r-rlang
    - r-rmarkdown
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-yaml
  run:
    - r-base
    - r-dplyr
    - r-fs
    - r-glue
    - r-knitr
    - r-nemo
    - r-r6
    - r-readr
    - r-rlang
    - r-rmarkdown
    - r-stringr
    - r-tibble
    - r-tidyr

tests:
  - r:
      libraries:
        - tidywigits
  - script:
    - tidywigits.R --version

about:
  homepage: https://github.com/umccr/tidywigits
  summary: WiGiTS workflow tidying
  description: WiGiTS workflow tidying
  license: MIT
  license_file: LICENSE
  repository: https://github.com/umccr/tidywigits
  documentation: https://umccr.github.io/tidywigits/

extra:
  recipe-maintainers:
    - pdiakumis
